import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight,Check } from 'lucide-react';
import { services } from '@/lib/brand';
import { AnalysisButton } from '@/components/providers';
import { ProductVisual } from '@/components/visuals';
import { Faq } from '@/components/faq';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return {title:s?.title||'Serviço',description:s?.description};}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const service=services.find(s=>s.slug===slug);if(!service)notFound();return <><section className="page-hero container service-hero"><div><p className="eyebrow">SOLUÇÕES / {service.number}</p><h1>{service.title}</h1><p className="page-hero-description">{service.description}</p><AnalysisButton source={service.slug}>Receber análise gratuita</AnalysisButton></div><div className="service-hero-visual"><ProductVisual variant={service.icon==="web"?0:service.icon==="layers"||service.icon==="chart"?1:2}/><span>{service.short}</span></div></section><section className="light-section section-pad"><div className="container service-detail-layout"><div><p className="eyebrow">A PERGUNTA CERTA</p><h2>{service.question}</h2><p>Entendemos o contexto antes de propor a solução. O escopo e as entregas são definidos a partir das necessidades reais do seu projeto.</p></div><div><p className="eyebrow">POSSIBILIDADES DO ESCOPO</p><ul className="deliverable-list">{service.deliverables.map(d=><li key={d}><Check size={20}/>{d}</li>)}</ul><p className="muted">Tecnologias, integrações, prazos e infraestrutura são acordados na proposta do projeto.</p></div></div></section><section className="service-next section-pad"><div className="container"><p className="eyebrow">OUTRAS POSSIBILIDADES</p><h2>O seu projeto pode<br/><span>conectar mais de uma solução.</span></h2><div className="related-services">{services.filter(s=>s.slug!==slug).slice(0,3).map(s=><Link key={s.slug} href={`/servicos/${s.slug}`}><span>{s.number}</span><h3>{s.title}</h3><ArrowUpRight size={24}/></Link>)}</div></div></section><Faq/></>;}
