"use client";
import { useState,useEffect,type FormEvent } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import ReactMarkdown from 'react-markdown';
import { ArrowUpRight,Plus,LogOut,Pencil,Trash2,LoaderCircle,Eye,FileText,Users,Briefcase } from 'lucide-react';
import type { Lead,Post,CaseStudy } from '@bravite/shared';
import { request } from '@/lib/api';
type Overview={leads:number;intents:number;posts:number;cases:number;pending_notifications:number;mail_configured:boolean;media_provider:string};
type Section='leads'|'posts'|'cases';
type Editor=Record<string,string>;
const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export default function Admin(){
 const [auth,setAuth]=useState<boolean|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [section,setSection]=useState<Section>('leads'),[overview,setOverview]=useState<Overview|null>(null),[leads,setLeads]=useState<Lead[]>([]),[posts,setPosts]=useState<Post[]>([]),[cases,setCases]=useState<CaseStudy[]>([]);
 const [editor,setEditor]=useState<Editor|null>(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{void request<{authenticated:boolean}>('admin/session').then(s=>setAuth(s.authenticated)).catch(()=>{setAuth(false);setError('Não foi possível conectar ao painel.');});},[]);
 async function refresh(){const [o,l,p,c]=await Promise.all([request<Overview>('admin/overview'),request<Lead[]>('admin/leads'),request<Post[]>('admin/posts'),request<CaseStudy[]>('admin/cases')]);setOverview(o);setLeads(l);setPosts(p);setCases(c);}
 useEffect(()=>{if(auth)void refresh().catch(e=>setError(e.message));},[auth]);
 async function login(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await request('admin/login',{method:'POST',body:JSON.stringify({email,password})});setPassword('');setAuth(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){await request('admin/logout',{method:'POST'});setAuth(false);setLeads([]);setPosts([]);setCases([]);setOverview(null);}
 function changeTab(tab:Section){if(editor&&!confirm('Descartar as alterações não salvas?'))return;setSection(tab);setEditor(null);setNotice('');setError('');}
 function edit(item?:Post|CaseStudy){const data:Editor={title:'',slug:'',excerpt:'',summary:'',client:'',content:'',category:'Estratégia',cover_url:'',cover_alt:'',website_url:'',status:'draft'};if(item)Object.entries(item).forEach(([k,v])=>{if(v!=null)data[k]=String(v);});setEditor(data);setPreview(false);setNotice('');setError('');}
 async function save(event:FormEvent){event.preventDefault();if(!editor)return;setBusy(true);setError('');
  const keys=section==='posts'?['title','slug','excerpt','content','category','cover_url','cover_alt','status']:['title','slug','client','summary','content','category','cover_url','cover_alt','website_url','status'];
  const body=Object.fromEntries(keys.map(k=>[k,editor[k]||((k==='cover_url'||k==='website_url')?null:'')]));
  try{await request(`admin/${section}${editor.id?'/'+editor.id:''}`,{method:editor.id?'PUT':'POST',body:JSON.stringify(body)});setEditor(null);await refresh();setNotice(editor.status==='published'?'Conteúdo publicado.':'Rascunho salvo.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');const form=new FormData();form.set('file',file);try{const media=await request<{url:string}>('media/upload',{method:'POST',body:form});setEditor(v=>v?{...v,cover_url:media.url}:v);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(id:string){if(!confirm(section==='leads'?'Excluir este lead e suas notificações?':'Excluir este conteúdo permanentemente?'))return;setBusy(true);try{await request(`admin/${section}/${id}`,{method:'DELETE'});await refresh();setNotice('Registro excluído.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(auth===null)return <main className="admin-loading"><LoaderCircle className="spin"/><p>Carregando painel…</p></main>;
 if(!auth)return <main className="admin-login"><Link href="/" className="brand-link"><Image src="/brand/logo-reverse.svg" alt="Bravite" width={760} height={110} style={{width:210,height:'auto'}}/></Link><form onSubmit={login}><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Um lugar para<br/>fazer evoluir.</h1><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-blue full-width" disabled={busy}>{busy?'Entrando…':'Entrar no painel'}<ArrowUpRight size={18}/></button><Link href="/" className="admin-return">Voltar ao site</Link></form></main>;
 return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/"><Image src="/brand/logo-reverse.svg" alt="Bravite" width={760} height={110} style={{width:190,height:'auto'}}/></Link><p className="eyebrow">PAINEL DE CONSTRUÇÃO</p><nav aria-label="Administração">{([['leads','Leads',Users],['posts','Insights',FileText],['cases','Cases',Briefcase]] as const).map(([key,label,Icon])=><button key={key} className={section===key?'active':''} onClick={()=>changeTab(key)}><Icon size={19}/>{label}</button>)}</nav><Link href="/" target="_blank" className="text-link">Ver o site<ArrowUpRight size={16}/></Link><button className="admin-logout" onClick={()=>void logout()}><LogOut size={17}/>Sair</button></aside><div className="admin-main"><header className="admin-title"><div><p className="eyebrow">BRAVITE / ADMIN</p><h1>{section==='leads'?'Conversas que começam.':section==='posts'?'Perspectivas para compartilhar.':'Construções para mostrar.'}</h1></div>{section!=='leads'&&!editor&&<button className="button button-blue" onClick={()=>edit()}><Plus size={18}/>{section==='posts'?'Novo insight':'Novo case'}</button>}</header>
  <div className="admin-stats">{[[overview?.leads||0,'Leads com contato'],[overview?.intents||0,'Interesses anônimos'],[overview?.posts||0,'Insights publicados'],[overview?.cases||0,'Cases publicados']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
  {overview&&!overview.mail_configured&&<div className="admin-info">Notificações por e-mail aguardam configuração SMTP. {overview.pending_notifications} pendente(s). Os pedidos já estão salvos no painel.</div>}
  {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}
  {editor?<form className="admin-editor" onSubmit={save}><div className="editor-toolbar"><h2>{editor.id?'Editar conteúdo':'Novo conteúdo'}</h2><button className="text-link" type="button" onClick={()=>setPreview(!preview)}>{preview?<FileText size={17}/>:<Eye size={17}/>} {preview?'Editar':'Prévia'}</button><button className="text-link" type="button" onClick={()=>{if(confirm('Descartar alterações não salvas?'))setEditor(null);}}>Cancelar</button></div>
   {preview?<div className="prose editor-preview"><h1>{editor.title||'Título do conteúdo'}</h1><ReactMarkdown>{editor.content}</ReactMarkdown></div>:<><div className="form-grid"><label>Título<input value={editor.title} minLength={5} maxLength={200} required onChange={e=>setEditor({...editor,title:e.target.value,...(!editor.id?{slug:slugify(e.target.value)}:{})})}/></label><label>Endereço (slug)<input value={editor.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" onChange={e=>setEditor({...editor,slug:e.target.value})}/></label></div><div className="form-grid"><label>Categoria<input value={editor.category} required minLength={2} maxLength={80} onChange={e=>setEditor({...editor,category:e.target.value})}/></label>{section==='cases'&&<label>Cliente<input value={editor.client} required minLength={2} maxLength={160} onChange={e=>setEditor({...editor,client:e.target.value})}/></label>}</div><label>Resumo<textarea rows={3} value={editor[section==='posts'?'excerpt':'summary']} minLength={10} maxLength={section==='posts'?400:500} required onChange={e=>setEditor({...editor,[section==='posts'?'excerpt':'summary']:e.target.value})}/></label><label>Conteúdo (Markdown)<textarea className="markdown-input" rows={15} value={editor.content} required minLength={20} maxLength={100000} onChange={e=>setEditor({...editor,content:e.target.value})}/></label><div className="form-grid"><label>Imagem de capa<input type="file" accept="image/png,image/jpeg,image/webp,image/avif" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/><span className="form-note">PNG, JPEG, WebP ou AVIF · até 8 MB · {overview?.media_provider==='cloudflare'?'Cloudflare Images':'armazenamento local de desenvolvimento'}</span></label><label>Descrição da imagem<input value={editor.cover_alt} maxLength={200} required={!!editor.cover_url&&editor.status==='published'} onChange={e=>setEditor({...editor,cover_alt:e.target.value})}/></label></div>{editor.cover_url&&<div className="editor-cover"><Image src={editor.cover_url} alt={editor.cover_alt||'Prévia da capa'} width={420} height={220}/><button type="button" className="text-link" onClick={()=>setEditor({...editor,cover_url:'',cover_alt:''})}>Remover capa</button></div>}{section==='cases'&&<label>Link do projeto (opcional)<input type="url" value={editor.website_url} onChange={e=>setEditor({...editor,website_url:e.target.value})}/></label>}</>}
   <div className="editor-actions"><label>Estado<select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}><option value="draft">Rascunho</option><option value="published">Publicado</option></select></label><button className="button button-blue" disabled={busy}>{busy?'Salvando…':'Salvar conteúdo'}<ArrowUpRight size={18}/></button></div></form>:section==='leads'?<div className="leads-list">{leads.length?leads.map(lead=><article key={lead.id} className="lead-card"><div className="lead-card-top"><div><h2>{lead.name}</h2><span>{lead.company||'Empresa não informada'} · {new Date(lead.created_at).toLocaleDateString('pt-BR')}</span></div><select aria-label={`Estado do lead de ${lead.name}`} value={lead.status} onChange={async e=>{try{await request(`admin/leads/${lead.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})});await refresh();}catch(err){setError((err as Error).message);}}}><option value="new">Novo</option><option value="contacted">Contato realizado</option><option value="qualified">Qualificado</option><option value="closed">Encerrado</option></select></div><p className="lead-service">{lead.service}</p><p className="lead-message">{lead.message}</p><div className="lead-contact"><a href={`mailto:${encodeURIComponent(lead.email||'')}`}>{lead.email}</a><a href={`https://wa.me/${lead.phone?.replace(/\D/g,'').startsWith('55')?lead.phone.replace(/\D/g,''):'55'+lead.phone?.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer">{lead.phone}<ArrowUpRight size={14}/></a><button className="delete-button" aria-label={`Excluir lead de ${lead.name}`} onClick={()=>void remove(lead.id)}><Trash2 size={17}/></button></div></article>):<div className="admin-empty"><Users size={32}/><h2>O próximo contato começa no site.</h2><p>Pedidos enviados pelo formulário aparecerão aqui.</p></div>}</div>:<div className="admin-content-list">{(section==='posts'?posts:cases).map(item=><article key={item.id}><div><span className={`status-label ${item.status}`}>{item.status==='published'?'Publicado':'Rascunho'}</span><h2>{item.title}</h2><p>{item.category} · /{section==='posts'?'blog':'cases'}/{item.slug}</p></div><div className="content-actions"><button className="icon-button" onClick={()=>edit(item)} aria-label={`Editar ${item.title}`}><Pencil size={19}/></button>{item.status==='published'&&<Link className="icon-button" href={`/${section==='posts'?'blog':'cases'}/${item.slug}`} target="_blank" aria-label={`Ver ${item.title}`}><ArrowUpRight size={19}/></Link>}<button className="icon-button delete-button" disabled={busy} onClick={()=>void remove(item.id)} aria-label={`Excluir ${item.title}`}><Trash2 size={19}/></button></div></article>)}{!(section==='posts'?posts:cases).length&&<div className="admin-empty"><Briefcase size={32}/><h2>Conte uma construção real.</h2><p>Publique somente projetos com autorização de uso e dados confirmados.</p></div>}</div>}
 </div></main>;
}
