export const brand = {
 name: "Bravite", email: "bravitetech@gmail.com", phone: "(24) 99911-9722", instagram: "https://www.instagram.com/bravite.br/",
 whatsapp: "https://wa.me/5524999119722?text=Ol%C3%A1%2C%20Bravite!%20Quero%20conversar%20sobre%20um%20projeto.",
 slogan: "Coragem para criar. Engenharia para evoluir.",
};
export const services = [
 {slug:"criacao-de-sites",title:"Criação de sites",short:"Presença que faz sentido.",description:"Sites institucionais e landing pages que traduzem a identidade da sua empresa e criam caminhos claros para o contato. A gestão de tráfego pago pode complementar o projeto, em parceria com profissionais de campanhas.",number:"01",icon:"web",deliverables:["Arquitetura de informação e conteúdo","Design responsivo e identidade visual","Implementação, acessibilidade e SEO técnico","Integração dos canais de contato","Landing pages e jornada de conversão para campanhas de Google Ads e Meta Ads","Mensuração conforme consentimento","Gestão de tráfego pago com parceiros, conforme o escopo"],question:"Como sua empresa deve ser percebida na web?"},
 {slug:"sistemas-web",title:"Sistemas web & plataformas",short:"Sua operação, conectada.",description:"Aplicações sob medida para organizar processos, conectar pessoas e transformar necessidades do negócio em ferramentas úteis.",number:"02",icon:"layers",deliverables:["Análise de processos e requisitos","Interfaces e fluxos de trabalho","Regras de negócio, API e banco de dados","Perfis de acesso e integrações"],question:"Qual processo merece funcionar melhor?"},
 {slug:"e-commerces",title:"E-commerces",short:"Uma jornada de compra bem construída.",description:"Lojas virtuais com navegação clara, catálogo organizado e integrações adequadas à operação comercial.",number:"03",icon:"bag",deliverables:["Organização do catálogo e da navegação","Experiência de produto e checkout","Integrações de pagamento e logística","Preparação técnica para operação"],question:"O que seu cliente precisa para comprar com confiança?"},
 {slug:"automacao-inteligencia-artificial",title:"Automação & inteligência artificial",short:"Menos repetição. Mais possibilidades.",description:"Bots inteligentes e autônomos, automações e integrações para apoiar tarefas, sempre com limites e critérios de acompanhamento definidos.",number:"04",icon:"spark",deliverables:["Mapeamento de tarefas e exceções","Bots e assistentes para jornadas específicas","Conexão entre ferramentas e dados","Critérios de supervisão e intervenção humana"],question:"Onde a tecnologia pode liberar tempo no seu negócio?"},
 {slug:"analise-de-dados",title:"Análise de dados para negócios",short:"Informação para decidir.",description:"Organização e análise de dados para transformar informações dispersas em uma visão mais clara da operação e de suas prioridades.",number:"05",icon:"chart",deliverables:["Entendimento das perguntas do negócio","Organização e integração das fontes","Indicadores e painéis de acompanhamento","Documentação e orientação de uso"],question:"Que decisão seus dados precisam ajudar a tomar?"},
] as const;
export const processSteps = [
 {title:"Analisar",label:"Análise do negócio",description:"Entendemos o contexto, o público-alvo e os objetivos. O primeiro entregável é clareza sobre o problema que vale resolver.",output:"Contexto, necessidades e objetivos",from:0,to:1,arrow:"Contexto e objetivos",returnArrow:"Diagnóstico e prioridades"},
 {title:"Estruturar",label:"Estratégia e escopo",description:"Traduzimos as necessidades em uma estratégia, com prioridades, requisitos e critérios de aceite alinhados com você.",output:"Estratégia e escopo definidos",from:1,to:2,arrow:"Requisitos e prioridades",returnArrow:"Escopo alinhado"},
 {title:"Desenhar",label:"Design e identidade",description:"Verificamos a identidade existente ou construímos a direção visual necessária. Desenhamos a experiência antes de desenvolver.",output:"Identidade e experiência aprovadas",from:2,to:3,arrow:"Experiência e identidade",returnArrow:"Validação do design"},
 {title:"Construir",label:"Desenvolvimento",description:"Implementamos a aplicação com tecnologias adequadas ao projeto, acompanhamento das decisões e infraestrutura acordada.",output:"Aplicação implementada",from:3,to:4,arrow:"Implementação e integrações",returnArrow:"Revisão das entregas"},
 {title:"Entregar",label:"Qualidade e entrega",description:"Validamos os critérios de qualidade, testamos os fluxos e fazemos as otimizações necessárias para uma entrega acompanhável.",output:"Entrega validada e próximos passos",from:4,to:0,arrow:"Testes e otimizações",returnArrow:"Entrega e orientação"},
] as const;
